### ISSUE TITLE
api文档乱码

### ISSUE THREAD

**Issue by fengke122** [H4rry217/AimRobot-api#1]
![img](https://github.com/H4rry217/AimRobot-api/assets/98901527/7bee6ba9-2739-4956-a2e5-e8701d1246e4)

**Comment by fengke122** [comment]
作者大大有进入房间的api功能吗 很想做一个自己的暖服机器人

**Comment by H4rry217** [comment]
已确认文档有问题，将会在之后更新

> ![img](https://user-images.githubusercontent.com/98901527/275452604-7bee6ba9-2739-4956-a2e5-e8701d1246e4.png)

**Comment by H4rry217** [comment]
> 作者大大有进入房间的api功能吗 很想做一个自己的暖服机器人

对应功能之后将会提供，不过可能需要一些时间

**Comment by H4rry217** [comment]
https://github.com/H4rry217/AimRobot-api/blob/master/docs/ApiDoc.md
